# Generated by Django 4.1.7 on 2023-03-29 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReClaimItApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
