# Generated by Django 4.1.7 on 2023-03-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReClaimItApp', '0002_alter_list_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
