# Generated by Django 4.1.7 on 2023-03-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReClaimItApp', '0003_alter_list_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='list',
            field=models.TextField(default='None'),
        ),
    ]
